# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in konfiguracja.gemspec
gemspec

gem "rake", "~> 13.0"

gem "maxitest", "~> 4.2"

gem "standard", "~> 1.3"
